name: release

on:
  workflow_dispatch:
    inputs:
      branch:
        description: Branch
        required: true
        default: main
        type: string
      namespace:
        description: Registry Namespace
        required: true
        type: string
      slug:
        description: Replicated App Slug
        required: true
        type: string
      version:
        description: Release Version
        required: true
        type: string
      proxy:
        description: Proxy Image Registry
        required: true
        default: proxy.replicated.com
        type: string

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
      id-token: write
    outputs:
      web-tags: ${{ steps.web-meta.outputs.tags }}
      web-digest: ${{ steps.build-web.outputs.digest }}
      nginx-tags: ${{ steps.nginx-meta.outputs.tags }}
      nginx-digest: ${{ steps.build-nginx.outputs.digest }}
    steps:
      - uses: actions/checkout@v4
        with:
          repository: slackernews/slackernews.git
          ref: ${{ inputs.branch }}
          token: ${{ secrets.GITHUB_TOKEN }} 

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for web image
        id: web-meta
        uses: docker/metadata-action@v5
        with:
          tags: |
                type=sha,format=long
                type=schedule
                type=raw,${{ inputs.version }}
                type=ref,event=branch
                type=ref,event=tag
                type=ref,event=pr
          images: ${{ env.REGISTRY }}/${{ inputs.namespace }}/slackernews-web

      - name: Extract metadata (tags, labels) for nginx image
        id: nginx-meta
        uses: docker/metadata-action@v5
        with:
          tags: |
                type=sha,format=long
                type=schedule
                type=raw,${{ inputs.version }}
                type=ref,event=branch
                type=ref,event=tag
                type=ref,event=pr
          images: ${{ env.REGISTRY }}/${{ inputs.namespace }}/slackernews-nginx

      - uses: int128/docker-build-cache-config-action@v1
        id: cache
        with:
          image: ghcr.io/${{ github.repository }}/cache

      - name: Build web image
        id: build-web
        uses: docker/build-push-action@v5
        with:
          context: ./slackernews
          tags: ${{ steps.web-meta.outputs.tags }}
          labels: ${{ steps.web-meta.outputs.labels }}
          file: ./deploy/Dockerfile.web
          push: true
          cache-from: ${{ steps.cache.outputs.cache-from }}
          cache-to: ${{ steps.cache.outputs.cache-to }}

      - name: Build nginx image
        id: build-nginx
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: ${{ steps.nginx-meta.outputs.tags }}
          labels: ${{ steps.nginx-meta.outputs.labels }}
          file: ./deploy/Dockerfile.nginx
          push: true
          cache-from: ${{ steps.cache.outputs.cache-from }}
          cache-to: ${{ steps.cache.outputs.cache-to }}


  sign:
    runs-on: ubuntu-22.04
    needs:
      - build
    permissions:
      contents: read
      packages: write
      id-token: write
    outputs:
      web-signature: ${{ steps.sign-web.outputs.signature }}
      nginx-signature: ${{ steps.sign-nginx.outputs.signature }}
    steps:
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.3.0

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Sign the web image
        id: sign-web
        run: |
          cosign sign ${{ env.REGISTRY }}/${{ inputs.namespace }}/slackernews-web@${{ needs.build.outputs.web-digest }} --yes
          echo "signature=$(cosign triangulate ${{ env.REGISTRY }}/${{ inputs.namespace }}/slackernews-web@${{ needs.build.outputs.web-digest }})" >> $GITHUB_OUTPUT

      - name: Sign the NGINX image
        id: sign-nginx
        run: |
          cosign sign ${{ env.REGISTRY }}/${{ inputs.namespace }}/slackernews-nginx@${{ needs.build.outputs.nginx-digest }} --yes
          echo "signature=$(cosign triangulate ${{ env.REGISTRY }}/${{ inputs.namespace }}/slackernews-nginx@${{ needs.build.outputs.nginx-digest }})" >> $GITHUB_OUTPUT

  release:
    runs-on: ubuntu-22.04
    needs:
      - sign
    steps:
      - uses: actions/checkout@v4
        with:
          repository: slackernews/slackernews.git
          ref: ${{ inputs.branch }}
          token: ${{ github.token }} 

      - id: embedded-cluster-version
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: replicatedhq
          repo: embedded-cluster
          excludes: prerelease, draft

      - run: make chart

      - uses: azure/setup-helm@v3
        with:
          version: "3.9.0"
        id: install

      - name: Update the values.yaml with the registry name
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          include: 'chart/slackernews/values.yaml'
          find: '$REGISTRY'
          replace: '${{ inputs.proxy }}'
          regex: false

      - name: Update the values.yaml with the image path
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          include: 'chart/slackernews/values.yaml'
          find: '$IMAGE'
          replace: 'proxy/${{ inputs.slug }}/${{ env.REGISTRY }}/${{ inputs.namespace }}/slackernews-web:${{ inputs.version }}'
          regex: false

      - name: Update the values.yaml with the image path
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          include: 'chart/slackernews/values.yaml'
          find: '$NGINX_IMAGE'
          replace: 'proxy/${{ inputs.slug }}/${{ env.REGISTRY }}/${{ inputs.namespace }}/slackernews-nginx:${{ inputs.version }}'
          regex: false

      - id: package-helm-chart
        run: |
          cd chart/slackernews && \
          helm dep up --debug && \
          cd .. && \
          helm package \
            --app-version=${{ inputs.version }} \
            --version=${{ inputs.version }} \
            ./slackernews


      - name: Copy the helm chart to the kots directory
        run: cp ./chart/slackernews-${{ inputs.version }}.tgz ./kots

      - name: Adds embedded cluster config
        run: |
          cat <<MANIFEST > ./kots/embedded-cluster.yaml
          apiVersion: embeddedcluster.replicated.com/v1beta1
          kind: Config
          spec:
            version: ${RELEASE}
            unsupportedOverrides:
              k0s: |
                config:
                  spec:
                    api:
                      extraArgs:
                        service-node-port-range: 80-32767
                    network:
                      calico:
                        wireguard: true
          MANIFEST
        env:
          RELEASE: ${{ steps.embedded-cluster-version.outputs.release }}

      - name: Set web image in HelmChart kind
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          include: 'kots/slackernews-chart.yaml'
          find: '$REGISTRY'
          replace: '${{ inputs.proxy }}'
          regex: false

      - name: Update chart version in HelmChart kind
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          include: 'kots/slackernews-chart.yaml'
          find: '$VERSION'
          replace: '${{ inputs.version }}'
          regex: false

      - name: Update chart version in HelmChart kind
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          include: 'kots/slackernews-chart.yaml'
          find: '$NAMESPACE'
          replace: '${{ inputs.namespace }}'
          regex: false

      - name: Provide web image to the airgap builder
        id: airgap-web-image
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.spec.builder.images.slackernews.repository = "ghcr.io/${{ inputs.namespace }}/slackernews-web:${{ inputs.version }}"' kots/slackernews-chart.yaml

      - name: Provide nginx image to the airgap builder
        id: airgap-nginx-image
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.spec.builder.images.nginx.repository = "ghcr.io/${{ inputs.namespace }}/slackernews-nginx:${{ inputs.version }}"' kots/slackernews-chart.yaml

      - name: Add web image signature to airgap bundle
        uses: mikefarah/yq@v4.40.5
        with:
          cmd: yq -i '.spec.additionalImages += [ "${{ needs.sign.outputs.web-signature }}" ]' kots/replicated-app.yaml

      - name: Add nginx image signature to airgap bundle
        uses: mikefarah/yq@v4.40.5
        with:
          cmd: yq -i '.spec.additionalImages += [ "${{ needs.sign.outputs.nginx-signature }}" ]' kots/replicated-app.yaml

      - name: Create the unstable release
        uses: replicatedhq/action-kots-release@configurable-endpoint
        with:
          replicated-app: ${{ inputs.slug }}
          replicated-api-token: ${{ secrets.REPLICATED_API_TOKEN }}
          replicated-api-origin: https://api.replicated.com/vendor
          yaml-dir: ./kots
          promote-channel: "Unstable"
          version: ${{ inputs.version }}
